---

- name: Configure | Install bundler
  shell: sudo gem install bundler
  args:
    creates: /usr/local/bin/bundler

- name: Configure | Install mongodb
  become: true
  ansible.builtin.package:
    name:
      - mongodb
    state: present
    update_cache: yes

- name: Configure | Start mongod service
  become: true
  ansible.builtin.service:
    name: mongodb
    state: started
    enabled: true

- name: Configure | Copy unit file for application
  become: true
  ansible.builtin.template:
    src: raddit.service.j2
    dest: /etc/systemd/system/raddit.service
    owner: root
    group: root
    mode: 0755
