---

- name: Deploy | Clone app repo
  ansible.builtin.git:
    repo: https://github.com/Artemmkin/raddit.git
    dest: "{{ home_dir }}/raddit"

- name: Deploy | Install dependent gems
  become: true
  bundler:
    state: present
    chdir: "{{ home_dir }}/raddit"

- name: Deploy | Start raddit service
  become: true
  ansible.builtin.service:
    name: raddit
    state: started
    enabled: true
