---

- name: Pre-run | Updating packages...
  hosts: all
  become: true
  pre_tasks:
    - name: Pre-run | update package cache (arch, manjaro)
      community.general.pacman:
        update_cache: yes
        upgrade: yes
      changed_when: false
      when: ansible_distribution == "Archlinux"

    - name: Pre-run | update package cache (debian, etc)
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        name: "*"
        state: latest
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Pre-run | update package cache (fedora)
      ansible.builtin.dnf:
        update_only: yes
        name: "*"
        state: latest
      changed_when: false
      when: ansible_distribution == "Fedora"

- name: Pre-configuring hosts...
  hosts: all
  become: true
  roles:
    - pre-configure

- name: Deploy server
  hosts: raddit-app
  roles:
    - configure
    - deploy

- name: Post-run | Cleanup hosts...
  hosts: all
  become: true
  vars_files:
    - roles/pre-configure/vars/main.yml
  tasks:
    - name: Post-cleanup | Packages (arch)
      ansible.builtin.shell: yes | pacman -Scc
      when: ansible_distribution == "Archlinux"

    - name: Post-cleanup | Packages' cache (debian and ubuntu)
      ansible.builtin.apt:
        autoclean: yes
      changed_when: false
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Post-cleanup | Autoremove orphan packages (debian and ubuntu)
      ansible.builtin.apt:
        autoremove: yes
        purge: yes
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Post-cleanup | Package's cache (fedora)
      ansible.builtin.dnf:
        autoremove: yes
      when: ansible_distribution == "Fedora"

    - name: community.general.telegram | Send completion alert
      ansible.builtin.include_tasks: roles/pre-configure/tasks/alerts/completion_alert.yml
      when:
        - task_failed is not defined

    - name: community.general.telegram | Send failure alert
      ansible.builtin.include_tasks: roles/pre-configure/tasks/alerts/failure_alert.yml
      when:
        - task_failed is defined
        - task_failed == true
